### ISSUE TITLE
Bug with negative Gain

### ISSUE THREAD

**Issue by VictuarVi** [rlkamalapurkar/bodeplot#13]
# Wrong starting phase

By plotting the following function:
```
\begin{BodePhPlot}[%
    axes/{height=4cm,
    width=10cm},
    ytick distance=90,
    ylabel={Fase (deg)}, xlabel={Frequenza (rad/s)}
    ]
    {0.01}
    {100}
    \addBodeZPKPlots[%
    true/{green, thick},
    linear/{draw=none},
    asymptotic/{orange,thick}%
    ]
    {phase}
    {%
    z/{0.9},
    p/{-0.2, -8},
    k/-0.5625%
    }
\end{BodePhPlot}
```

The starting phase should be -180° ($\Re (k) < 0$), while the plot starts at phase 0°:
![image](https://github.com/user-attachments/assets/e30f155e-0ae6-4e00-8d8d-07cbb0a4314d)

also, as you can tell, the zeroes and poles have a "slight off" line. It should be perfectly straight, but it isn't. The transfer function is:
$$G(s) = \frac{(-0.9+s)}{(s+0.2)(s+8)}$$
which, from by calculations, has:
- Poles: $s = -0.2, -8$
- Zeroes: $s = 0.9$
- Gain: $k = -\frac{0.9}{1.6} \approx 0.5625$

For some reason, the magnitude plot too is incorrect:
```
\begin{BodeMagPlot}[%
    axes/{height=4cm,
    width=10cm,ytick distance=5, ylabel={Guadagno (dB)}, xlabel={Frequenza (rad/s)}},
    ]
    {0.01}
    {100}
    \addBodeZPKPlots[%
    true/{draw=none},
    linear/{draw=none},
    asymptotic/{orange,thick}%
    ]
    {magnitude}
    {%
    z/{0.9},
    p/{-0.2, -8},
    k/-0.5625%
    }
    \end{BodeMagPlot}
```
![image](https://github.com/user-attachments/assets/f557a99a-ef87-48d2-9668-ad1f5a76ac39)
because $20 \log_{10} (|-0.5625|) \approx -5 \text{ dB}$, not $-10$ as seen in the plot.

However, if I change the gain to $k = 1$, the plot becomes correct:
```
\begin{BodeMagPlot}[%
    axes/{height=4cm,
    width=10cm,ytick distance=5, ylabel={Guadagno (dB)}, xlabel={Frequenza (rad/s)}},
    ]
    {0.01}
    {100}
    \addBodeZPKPlots[%
    true/{draw=none},
    linear/{draw=none},
    asymptotic/{orange,thick}%
    ]
    {magnitude}
    {%
    z/{0.9},
    p/{-0.2, -8},
    k/1%
    }
    \end{BodeMagPlot}
```
![image](https://github.com/user-attachments/assets/dc6da46c-97d9-4fb6-94d2-a6a3f6e01507)

**Comment by rlkamalapurkar** [comment]
```
z/{0.9},
p/{-0.2, -8},
k/-0.5625%
```
Gives you the Bode plot of $$G(s) = \frac{-0.5625(-0.9+s)}{(s+0.2)(s+8)}$$, not $$G(s) = \frac{(-0.9+s)}{(s+0.2)(s+8)}$$.

If you want Bode plot of $$G(s) = \frac{(-0.9+s)}{(s+0.2)(s+8)}$$, then k should be 1.

The ZPK form I used is similar to MATLAB, where k is not the DC gain of the system.

**Comment by rlkamalapurkar** [comment]
The lines not being exactly straight is a consequence of sampling. If you increase the number of samples by adding, say samples=200 to the plot options, the asymptotic plot will look better.

**Comment by VictuarVi** [comment]
Oh wow, thanks! it works (both of the solutions you posted).

I just have one last question. According to the documentation, if I write:
```
\begin{BodeMagPlot}[%
    axes/{
        ytick distance=10,
        height=4cm,width=10cm,
        xlabel={Frequenza (rad/s)},
        ylabel={Guadagno (dB)},
        },
    commands/{\node at (axis cs: 0.9,-20) [circle,fill,inner sep=0.05cm label=below left:{$p_i$}]{};}
    ]
[...]
```
in the options of `BodeMagPlot`, a note should appear. That's nearly the same syntax as the one used in the example of `BodeTF` (except without the `mag/` part).

Despite that, LaTeX returns the error: `Package pgfkeys: I do not know the key '/tikz/commands' and I am going to ignore it. Perhaps you misspelled it.`.

**Comment by rlkamalapurkar** [comment]
I did not add the `commands` option to any environments since you can simply add the `tikz` code inside the environment itself.
```
\begin{BodeMagPlot}[%
    axes/{
        ytick distance=10,
        height=4cm,width=10cm,
        xlabel={Frequenza (rad/s)},
        ylabel={Guadagno (dB)},
        },
    ]
    \node at (axis cs: 0.9,-20) [circle,fill,inner sep=0.05cm label=below left:{$p_i$}]{};
[...]
\end{BodeMagPlot}
```

**Comment by VictuarVi** [comment]
Thanks. It works.
