### ISSUE TITLE
Error in double axis

### ISSUE THREAD

**Issue by AndreaDiPietro92** [rlkamalapurkar/bodeplot#2]
Watching the `TL-DR.pdf` there is a problem with the "Multiple Nichols charts", in particular the double x axis:

![image](https://user-images.githubusercontent.com/36949583/140603021-d58cb135-2f02-4b8d-b497-66ea5cd9754e.png)

**Comment by rlkamalapurkar** [comment]
Thank you, this was due to incorrect parsing of the `x tick distance` and `y tick distance` options. This should be fixed in v1.0.4.
