### ISSUE TITLE
Interferance with plot

### ISSUE THREAD

**Issue by AndreaDiPietro92** [rlkamalapurkar/bodeplot#3]
Hi :wave:! Trying to plot a function with `TiKZ` (with bode plot loaded) i gets several errors in compilation. Removing the package all the errors disappears.

Code for testing
```
\documentclass{standalone}
\usepackage{amsmath}
\usepackage{pgf,tikz}
\usepackage{pgfplots}
\usepackage{siunitx}
\pgfplotsset{compat=newest}

%\usepackage{bodeplot}

\begin{document}

		\begin{tikzpicture}
		% sin
		\draw[line width=2pt, blue]
		plot[domain=0:2*pi, samples=100] (\x/3,{sin(\x r)});

		
	\end{tikzpicture}
	
\end{document}
```

With the `%\usepackage{bodeplot}` all works otherwise i get 
![image](https://user-images.githubusercontent.com/36949583/142223804-4538b12d-3a29-414b-b84e-7a5774b9dc2e.png)

**Comment by rlkamalapurkar** [comment]
This error is a result of me setting the `/pgfplots/variable` key to `t` in the package. Not sure about the best way to address this yet. In the meantime, just add `variable=\x` to your plot command.
```
\documentclass{standalone}
\usepackage{bodeplot}
\pgfplotsset{compat=newest}
\begin{document}
	\begin{tikzpicture}
		\draw[line width=2pt, blue] 
		plot [domain=0:2*pi, samples=100,variable=\x] (\x/3,{sin(\x r)});
	\end{tikzpicture}
\end{document}
```
