### ISSUE TITLE
pgf option doesn't work in conjunction with \usepackage pgfplots

### ISSUE THREAD

**Issue by erwindenboer** [rlkamalapurkar/bodeplot#7]
Hello,

When I use this package as follows (\usepackage[pgf]{bodeplot}) in conjunction with \usepackage{pgfplots} I get the following output:

![image](https://user-images.githubusercontent.com/31764383/190510823-abfd30e7-110b-49fe-b6f3-359bb4e1ff91.png)

But when I exclude \usepackage[pgf]{bodeplot} I get the intended output:

![image](https://user-images.githubusercontent.com/31764383/190511094-5aefed0e-d30f-40da-bfec-f57f19da69f8.png)

In your package, there is some interference with pgfplots

**Comment by rlkamalapurkar** [comment]
This package already loads `pgfplots` package with `compat=1.18`. You do not need to load it separately using `\usepackage`.

I am afraid it might have to do with your \usepackage{pgfplots} command overriding the `compat=1.18` compatibility setting. If that is the case, there is nothing I can do. The `bodeplot` package needs `pgfplots` 1.18 or newer.

That being said, I will look into the issue if you can tell me the exact commands you are using to generate the plots above.
