### ISSUE TITLE
Parameter for y-axis limits

### ISSUE THREAD

**Issue by patzf** [rlkamalapurkar/bodeplot#9]
I guess this is by design and intentional that the y-axes limit are automatically computed and chosen. Still, it would be nice to have the option to pass ymin, ymax to the plots, similar to the limtis of the x axes. Did I oversee that option?

**Comment by rlkamalapurkar** [comment]
All commands and environments are set up to pass options to the underlying `pgfplots` commands and environments. For example, `axes/mag/{options}` will pass `options` to the `semilogaxis` environment of the magnitude plot and `axes/ph/{options}` will pass `options` to the `semilogaxis` environment of the phase plot. You can pass any options accepted by the  `semilogaxis` environment there, including `ymin` and `ymax`. The example below uses `\BodeZPK` but a similar approach should work with all `bodeplot` commands and environments.

```
 \BodeZPK[%
     plot/mag/{red,thick},
     plot/ph/{blue,thick},
     axes/mag/{%
         ytick distance=40,
         ymin = -120,
         ymax = 80,
     },
     axes/ph/{%
         ytick distance=90,
         ymin = 0,
         ymax = 360
     },
     approx/linear%
 ]{%
     z/{0,{-0.1,-0.5},{-0.1,0.5}},
     p/{{-0.5,-10},{-0.5,10}},
     k/10 %
 } {0.01} {100}
```
